FROM python:3.11-slim

WORKDIR /src

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip

COPY requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir -r /src/requirements.txt

RUN pip install --no-cache-dir celery[redis] eventlet

COPY . .

ENV PYTHONPATH=/src

CMD ["celery", "-A", "src.parsing_movie.celery.celery_app", "worker", "--loglevel=info"]