version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/src
    command: celery -A src.parsing_movie.celery:celery_app worker --loglevel=info