FROM python:3.11-slim

WORKDIR /src

# ✅ системные зависимости (добавили libxml2 + libxslt)
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libxml2-dev \
    libxslt1-dev \
    && rm -rf /var/lib/apt/lists/*

# обновляем pip
RUN pip install --no-cache-dir --upgrade pip

# ставим зависимости (кэшируем слой)
COPY requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir -r /src/requirements.txt

# celery зависимости
RUN pip install --no-cache-dir celery[redis] eventlet

# копируем проект
COPY . .

ENV PYTHONPATH=/src

# запуск worker
CMD ["celery", "-A", "src.parsing_movie.celery:celery_app", "worker", "--loglevel=info"]