services:
  postgres:
    image: postgres:16
    container_name: cinema-postgres
    restart: always
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_pass
      POSTGRES_DB: cinema_db
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-host=trust"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "max_connections=200"
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cinema_user -d cinema_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: telegram_bot_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

  browserless:
    image: browserless/chrome:latest
    container_name: telegram_bot_browserless
    ports:
      - "3000:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=5
      - CONNECTION_TIMEOUT=600000
      - PREBOOT_CHROME=true
      - LOG_LEVEL=info
      - DEFAULT_LAUNCH_ARGS=["--disable-logging"]
    networks:
      - app_network
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: telegram_bot_celery_worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      browserless:
        condition: service_started
    env_file:
      - .env
    environment:
      - PYTHONPATH=/src
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REMOTE_SELENIUM_URL=http://browserless:3000/webdriver
    command: celery -A src.parsing_movie.celery:celery_app worker --loglevel=info --concurrency=1
    volumes:
      - .:/src
    networks:
      - app_network
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    entrypoint: [ "/src/entrypoint.bot.sh" ]
    container_name: telegram_bot_app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      browserless:
        condition: service_started
    env_file:
      - .env
    environment:
      - PYTHONPATH=/src
      - REMOTE_SELENIUM_URL=http://browserless:3000/webdriver
    volumes:
      - .:/src
    networks:
      - app_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: telegram_bot_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    name: telegram_bot_network
    driver: bridge

volumes:
  postgres_data:
