services:
  browserless:
    image: browserless/chrome:latest
    container_name: telegram_bot_browserless
    ports:
      - "3000:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=1
      - CONNECTION_TIMEOUT=600000
      - PREBOOT_CHROME=true
      - LOG_LEVEL=info
      - DEFAULT_LAUNCH_ARGS=["--disable-logging"]
    networks:
      - moscow_network
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: telegram_bot_celery_worker
    depends_on:
      browserless:
        condition: service_started
    env_file:
      - .env
    environment:
      - PYTHONPATH=/src
      - LOG_FORMAT=json
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - REMOTE_SELENIUM_URL=http://browserless:3000/webdriver
      - SERVICE_NAME=celery-worker
      - SERVER_LOCATION=moscow
    labels:
      logging: "promtail"
      service: "celery-worker"
      server: "moscow"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: celery -A src.parsing_movie.celery:celery_app worker --loglevel=info --concurrency=1
    volumes:
      - .:/src
    networks:
      - moscow_network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail-moscow
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./observability/promtail/promtail-moscow.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    labels:
      logging: "promtail"
      service: "promtail"
      server: "moscow"
    networks:
      - moscow_network
    restart: unless-stopped

networks:
  moscow_network:
    driver: bridge
